# Generated by Django 4.2.3 on 2023-07-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_is_viewable'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_about_sovereignty',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, choices=[('politiques', 'politiques'), ('economies', 'economies'), ('security', 'security'), ('sovereignty', 'sovereignty'), ('other', 'other')], max_length=60),
        ),
    ]
